from app.objects.position import Position
from app.objects.abstract_object import AbstractObject
from app.objects.abstract_color_object import AbstractColorObject
from app.objects.abstract_image_object import AbstractImageObject
from app.objects.castle import Castle
from app.objects.pond import Pond
from app.objects.neutral import Neutral
from app.objects.abstract_craftsman import AbstractCraftsman
from app.objects.craftsman_a import CraftsmanA
from app.objects.craftsman_b import CraftsmanB
from app.objects.wall_a import WallA
from app.objects.wall_b import WallB
