INIT_WIDTH = 1100
INIT_HEIGHT = 800
INFO_BOARD_WIDTH = 300

MAX_DISTANCE = 1000


class Color:
    NEUTRAL_COLOR = "white"
    POND_COLOR = "black"
    BORDER_COLOR = "red"
    CHOOSE_COLOR = "yellow"
    WALL_A_COLOR = "#ADD8E6"
    WALL_B_COLOR = "pink"


colors = Color

CURRENT_TURN = "current_turn"
ACTIONS_LIST = "actions_list"

MAX_NUM_OF_CELLS_IN_WIDTH = 25
MAX_NUM_OF_CELLS_IN_HEIGHT = 25

MAX_NUMBER_OF_OBJECT = 5
MIN_NUMBER_OF_OBJECT = 1
